// generated by Fast Light User Interface Designer (fluid) version 1,0400

#ifndef SymbolDialogUI_h
#define SymbolDialogUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_Multiline_Input.H"
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Toggle_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>

class SymbolDialogUI {
public:
  SymbolDialogUI();
  Fl_Multiline_Input *_pLabelText;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
  Fl_Toggle_Button *btnDecision;
};
#endif
