// generated by Fast Light User Interface Designer (fluid) version 1,0400

#include "SymbolDialogUI.h"

SymbolDialogUI::SymbolDialogUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(570, 230);
    w = o; if (w) {/* empty */}
    o->color((Fl_Color)53);
    o->user_data((void*)(this));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { _pLabelText = new Fl_Multiline_Input(208, 12, 182, 47, "Enter symbol\'s label text: ");
      _pLabelText->box(FL_FLAT_BOX);
      _pLabelText->color(FL_BACKGROUND2_COLOR);
      _pLabelText->selection_color(FL_SELECTION_COLOR);
      _pLabelText->labeltype(FL_NORMAL_LABEL);
      _pLabelText->labelfont(1);
      _pLabelText->labelsize(13);
      _pLabelText->labelcolor(FL_FOREGROUND_COLOR);
      _pLabelText->textsize(13);
      _pLabelText->align(Fl_Align(FL_ALIGN_LEFT));
      _pLabelText->when(FL_WHEN_RELEASE);
    } // Fl_Multiline_Input* _pLabelText
    { Fl_Tabs* o = new Fl_Tabs(14, 75, 536, 100);
      o->box(FL_FLAT_BOX);
      o->selection_color((Fl_Color)135);
      { Fl_Group* o = new Fl_Group(14, 100, 536, 80, "Decision");
        o->box(FL_FLAT_BOX);
        o->color(FL_LIGHT2);
        o->selection_color((Fl_Color)53);
        o->labelsize(13);
        { Fl_Box* o = new Fl_Box(16, 112, 263, 22, "Connect YES branche with symbol: ");
          o->labelfont(1);
          o->labelsize(13);
        } // Fl_Box* o
        { Fl_Box* o = new Fl_Box(17, 147, 257, 22, "Connect NO branche with symbol: ");
          o->labelfont(1);
          o->labelsize(13);
        } // Fl_Box* o
        { btnDecision = new Fl_Toggle_Button(278, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(311, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(344, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(377, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(410, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(443, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(476, 109, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(278, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(311, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(344, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(377, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(410, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(443, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(476, 144, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(15, 100, 535, 75, "Other Symbols");
        o->box(FL_FLAT_BOX);
        o->color(FL_LIGHT2);
        o->selection_color((Fl_Color)53);
        o->labelsize(13);
        o->hide();
        { Fl_Box* o = new Fl_Box(26, 129, 263, 22, "Connect with symbol: ");
          o->labelfont(1);
          o->labelsize(13);
        } // Fl_Box* o
        { btnDecision = new Fl_Toggle_Button(288, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(321, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(354, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(387, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(420, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(453, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        { btnDecision = new Fl_Toggle_Button(486, 124, 30, 30, "d");
          btnDecision->box(FL_FLAT_BOX);
          btnDecision->color(FL_BACKGROUND_COLOR);
          btnDecision->selection_color(FL_BACKGROUND_COLOR);
          btnDecision->labeltype(FL_NORMAL_LABEL);
          btnDecision->labelfont(0);
          btnDecision->labelsize(14);
          btnDecision->labelcolor(FL_FOREGROUND_COLOR);
          btnDecision->align(Fl_Align(FL_ALIGN_CENTER));
          btnDecision->when(FL_WHEN_RELEASE);
        } // Fl_Toggle_Button* btnDecision
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { new Fl_Return_Button(15, 195, 72, 25, "OK");
    } // Fl_Return_Button* o
    { new Fl_Button(90, 195, 70, 25, "Cancel");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
}
